name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: build artifacts
        shell: pwsh
        run: ./build/pack.ps1

      - name: attach to release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: dist/*

      - name: publish to nuget
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        if: env.NUGET_API_KEY != ''
        run: dotnet nuget push "dist/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
